# Generated by Django 4.2 on 2026-04-16 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='address',
            field=models.TextField(blank=True, db_column='adres'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(db_column='miasto', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_utworzenia'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(db_column='email', max_length=254),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='first_name',
            field=models.CharField(db_column='imie', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(db_column='nazwisko', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(db_column='telefon', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='postal_code',
            field=models.CharField(db_column='kod_pocztowy', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='data_aktualizacji'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(db_column='uzytkownik_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='voivodeship',
            field=models.CharField(blank=True, db_column='wojewodztwo', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_utworzenia'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_column='czy_przeczytane', default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, db_column='link', help_text='Opcjonalny link do szczególow'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(db_column='tresc'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(db_column='tytul', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Informacja'), ('warning', 'Ostrzeżenie'), ('success', 'Sukces'), ('error', 'Błąd')], db_column='typ', default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(db_column='uzytkownik_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='address',
            field=models.TextField(db_column='adres'),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='city',
            field=models.CharField(db_column='miasto', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='company_name',
            field=models.CharField(db_column='nazwa_firmy', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_utworzenia'),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='description',
            field=models.TextField(blank=True, db_column='opis'),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='email',
            field=models.EmailField(db_column='email', max_length=254),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='is_active',
            field=models.BooleanField(db_column='czy_aktywny', default=True),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='is_verified',
            field=models.BooleanField(db_column='czy_zweryfikowany', default=False),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='nip',
            field=models.CharField(blank=True, db_column='nip', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='phone',
            field=models.CharField(db_column='telefon', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='postal_code',
            field=models.CharField(db_column='kod_pocztowy', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='specializes_in',
            field=models.CharField(blank=True, db_column='specjalizacje', help_text='Specjalizacje, np. TV, Smartfony, Tablety', max_length=500),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='data_aktualizacji'),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='user',
            field=models.OneToOneField(db_column='uzytkownik_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='voivodeship',
            field=models.CharField(db_column='wojewodztwo', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_utworzenia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_column='telefon', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('client', 'Klient'), ('service', 'Serwis')], db_column='rola', default='client', max_length=10),
        ),
        migrations.AlterModelTable(
            name='clientprofile',
            table='klienci',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='powiadomienia',
        ),
        migrations.AlterModelTable(
            name='serviceprofile',
            table='serwisy',
        ),
        migrations.AlterModelTable(
            name='user',
            table='uzytkownicy',
        ),
    ]
