# Generated by Django 4.2 on 2026-04-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kategoria urządzenia',
                'verbose_name_plural': 'Kategorie urządzeń',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='zgloszenia.devicecategory')),
            ],
            options={
                'verbose_name': 'Typ urządzenia',
                'verbose_name_plural': 'Typy urządzeń',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Opis usterki')),
                ('device_brand', models.CharField(max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_status', models.BooleanField(default=False, help_text='Czy urządzenie jest na gwarancji?')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('normal', 'Normalny'), ('high', 'Wysoki'), ('urgent', 'Pilny')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('submitted', 'Zgłoszone'), ('viewed_by_services', 'Wyświetlone przez serwisy'), ('offers_received', 'Otrzymano oferty'), ('in_progress', 'W naprawie'), ('completed', 'Zakończone'), ('cancelled', 'Anulowane')], default='draft', max_length=20)),
                ('voivodeship', models.CharField(help_text='Województwo - dla filtrowania serwisów', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True)),
                ('is_mobile_service', models.BooleanField(default=False, help_text='Czy serwis ma dojechać do klienta?')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Lista URL do zdjęć')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='users.clientprofile')),
                ('device_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgloszenia.devicecategory')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgloszenia.devicetype')),
            ],
            options={
                'verbose_name': 'Zgłoszenie naprawy',
                'verbose_name_plural': 'Zgłoszenia napraw',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.clientprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.serviceprofile')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='zgloszenia.servicerequest')),
            ],
            options={
                'verbose_name': 'Opinia',
                'verbose_name_plural': 'Opinie',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='zgloszenia.servicerequest')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='zgloszenia.servicerequest')),
            ],
            options={
                'verbose_name': 'Wyświetlenie zgłoszenia',
                'verbose_name_plural': 'Wyświetlenia zgłoszeń',
                'unique_together': {('service_request', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Wiadomość od serwisu do klienta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.CharField(help_text='Szacowany czas naprawy', max_length=100)),
                ('warranty_period', models.CharField(blank=True, help_text='Okres gwarancji na naprawę', max_length=100)),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('accepted', 'Zaakceptowana'), ('rejected', 'Odrzucona'), ('withdrawn', 'Wycofana')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.serviceprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='zgloszenia.servicerequest')),
            ],
            options={
                'verbose_name': 'Oferta serwisu',
                'verbose_name_plural': 'Oferty serwisów',
                'ordering': ['-created_at'],
                'unique_together': {('service_request', 'service')},
            },
        ),
    ]
