# Generated by Django 4.2 on 2026-04-16 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zgloszenia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kwota naprawy', max_digits=10)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0, help_text='Prowizja administratora', max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Kwota dla serwisu (amount - admin_fee)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('paid_to_admin', 'Opłacone - u administratora'), ('released_to_service', 'Wypłacone serwisowi'), ('refunded', 'Zwrócone klientowi'), ('cancelled', 'Anulowane')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Przelew bankowy'), ('card', 'Karta płatnicza'), ('paypal', 'PayPal'), ('cash', 'Gotówka')], max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Kiedy klient zapłacił', null=True)),
                ('released_at', models.DateTimeField(blank=True, help_text='Kiedy wypłacono serwisowi', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='Kiedy zwrócono klientowi', null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='ID transakcji zewnętrznej', max_length=100)),
                ('admin_notes', models.TextField(blank=True, help_text='Notatki administratora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released_by', models.ForeignKey(blank=True, help_text='Administrator który zatwierdził wypłatę', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payments', to=settings.AUTH_USER_MODEL)),
                ('service_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='zgloszenia.serviceoffer')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='zgloszenia.servicerequest')),
            ],
            options={
                'verbose_name': 'Płatność',
                'verbose_name_plural': 'Płatności',
                'ordering': ['-created_at'],
            },
        ),
    ]
