# Generated by Django 4.2 on 2026-04-16 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_clientprofile_address_alter_clientprofile_city_and_more'),
        ('zgloszenia', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='name',
            field=models.CharField(db_column='nazwa', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='slug',
            field=models.SlugField(db_column='slug', unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='category',
            field=models.ForeignKey(db_column='kategoria_id', on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='zgloszenia.devicecategory'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(db_column='nazwa', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='slug',
            field=models.SlugField(db_column='slug', unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(db_column='tresc'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_utworzenia'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_column='czy_przeczytana', default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(db_column='odbiorca_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_column='nadawca_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='service_request',
            field=models.ForeignKey(db_column='zgloszenie_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='zgloszenia.servicerequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admin_fee',
            field=models.DecimalField(db_column='prowizja', decimal_places=2, default=0, help_text='Prowizja administratora', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, db_column='notatki', help_text='Notatki administratora'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(db_column='kwota', decimal_places=2, help_text='Kwota naprawy', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_utworzenia'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='final_amount',
            field=models.DecimalField(db_column='kwota_koncowa', decimal_places=2, help_text='Kwota dla serwisu (amount - admin_fee)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_column='data_zaplaty', help_text='Kiedy klient zapłacił', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Przelew bankowy'), ('card', 'Karta płatnicza'), ('paypal', 'PayPal'), ('cash', 'Gotówka')], db_column='metoda_platnosci', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, db_column='data_zwrotu', help_text='Kiedy zwrócono klientowi', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='released_at',
            field=models.DateTimeField(blank=True, db_column='data_wyplaty', help_text='Kiedy wypłacono serwisowi', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='released_by',
            field=models.ForeignKey(blank=True, db_column='zatwierdzony_przez_id', help_text='Administrator który zatwierdził wypłatę', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_offer',
            field=models.ForeignKey(db_column='oferta_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='zgloszenia.serviceoffer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_request',
            field=models.OneToOneField(db_column='zgloszenie_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='zgloszenia.servicerequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekująca'), ('paid_to_admin', 'Opłacone - u administratora'), ('released_to_service', 'Wypłacone serwisowi'), ('refunded', 'Zwrócone klientowi'), ('cancelled', 'Anulowane')], db_column='status', default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_column='id_transakcji', help_text='ID transakcji zewnętrznej', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='data_aktualizacji'),
        ),
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(db_column='klient_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.clientprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, db_column='komentarz'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_utworzenia'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_column='ocena'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(db_column='serwis_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.serviceprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service_request',
            field=models.OneToOneField(db_column='zgloszenie_id', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='zgloszenia.servicerequest'),
        ),
        migrations.AlterField(
            model_name='review',
            name='would_recommend',
            field=models.BooleanField(db_column='czy_poleca', default=True),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='additional_info',
            field=models.TextField(blank=True, db_column='dodatkowe_info'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_utworzenia'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='estimated_time',
            field=models.CharField(db_column='szacowany_czas', help_text='Szacowany czas naprawy', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='message',
            field=models.TextField(db_column='wiadomosc', help_text='Wiadomość od serwisu do klienta'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='price',
            field=models.DecimalField(db_column='cena', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='service',
            field=models.ForeignKey(db_column='serwis_id', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.serviceprofile'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='service_request',
            field=models.ForeignKey(db_column='zgloszenie_id', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='zgloszenia.servicerequest'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekująca'), ('accepted', 'Zaakceptowana'), ('rejected', 'Odrzucona'), ('withdrawn', 'Wycofana')], db_column='status', default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='data_aktualizacji'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='warranty_period',
            field=models.CharField(blank=True, db_column='okres_gwarancji', help_text='Okres gwarancji na naprawę', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.TextField(blank=True, db_column='adres'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='city',
            field=models.CharField(db_column='miasto', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(db_column='klient_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='users.clientprofile'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_column='data_zakonczenia', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_utworzenia'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(db_column='opis', help_text='Opis usterki'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='device_brand',
            field=models.CharField(db_column='marka_urzadzenia', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='device_category',
            field=models.ForeignKey(db_column='kategoria_urzadzenia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgloszenia.devicecategory'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='device_model',
            field=models.CharField(blank=True, db_column='model_urzadzenia', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='device_type',
            field=models.ForeignKey(blank=True, db_column='typ_urzadzenia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgloszenia.devicetype'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='estimated_budget',
            field=models.DecimalField(blank=True, db_column='szacowany_budzet', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='is_mobile_service',
            field=models.BooleanField(db_column='czy_serwis_mobile', default=False, help_text='Czy serwis ma dojechać do klienta?'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='photos',
            field=models.JSONField(blank=True, db_column='zdjecia', default=list, help_text='Lista URL do zdjęć'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='postal_code',
            field=models.CharField(db_column='kod_pocztowy', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Niski'), ('normal', 'Normalny'), ('high', 'Wysoki'), ('urgent', 'Pilny')], db_column='priorytet', default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='purchase_date',
            field=models.DateField(blank=True, db_column='data_zakupu', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='serial_number',
            field=models.CharField(blank=True, db_column='numer_seryjny', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('submitted', 'Zgłoszone'), ('viewed_by_services', 'Wyświetlone przez serwisy'), ('offers_received', 'Otrzymano oferty'), ('in_progress', 'W naprawie'), ('completed', 'Zakończone'), ('cancelled', 'Anulowane')], db_column='status', default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_column='data_zgloszenia', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(db_column='tytul', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='data_aktualizacji'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='voivodeship',
            field=models.CharField(db_column='wojewodztwo', help_text='Województwo - dla filtrowania serwisów', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='warranty_status',
            field=models.BooleanField(db_column='czy_gwarancja', default=False, help_text='Czy urządzenie jest na gwarancji?'),
        ),
        migrations.AlterField(
            model_name='servicerequestview',
            name='service',
            field=models.ForeignKey(db_column='serwis_id', on_delete=django.db.models.deletion.CASCADE, to='users.serviceprofile'),
        ),
        migrations.AlterField(
            model_name='servicerequestview',
            name='service_request',
            field=models.ForeignKey(db_column='zgloszenie_id', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='zgloszenia.servicerequest'),
        ),
        migrations.AlterField(
            model_name='servicerequestview',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, db_column='data_wyswietlenia'),
        ),
        migrations.AlterModelTable(
            name='devicecategory',
            table='kategorie_urzadzen',
        ),
        migrations.AlterModelTable(
            name='devicetype',
            table='typy_urzadzen',
        ),
        migrations.AlterModelTable(
            name='message',
            table='wiadomosci',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='platnosci',
        ),
        migrations.AlterModelTable(
            name='review',
            table='opinie',
        ),
        migrations.AlterModelTable(
            name='serviceoffer',
            table='oferty_serwisow',
        ),
        migrations.AlterModelTable(
            name='servicerequest',
            table='zgloszenia_naprawy',
        ),
        migrations.AlterModelTable(
            name='servicerequestview',
            table='wyswietlenia_zgloszen',
        ),
    ]
